name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  # This will execute the existing tests

  deploy:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in workspace
        shell: pwsh
        run: Get-ChildItem -Path . -Recurse

      - name: Install PowerShell Core
        run: pwsh -c "Write-Output 'Using PowerShell Core'"

      - name: Run deployment script
        shell: pwsh
        working-directory: .github
        run: ./deploy_script.ps1

      - name: Download Nginx
        run: Invoke-WebRequest -Uri "https://nginx.org/download/nginx-1.25.3.zip" -OutFile "nginx.zip"

      - name: Extract Nginx
        run: Expand-Archive -Path nginx.zip -DestinationPath C:\nginx -Force

      - name: Ensure Nginx Extracted Correctly
        shell: pwsh
        run: |
          if (Test-Path -Path "C:\nginx\nginx-1.25.3\") {
            Write-Output "✅ Nginx extracted successfully."
          } else {
            Write-Error "❌ Nginx extraction failed."
          }

      - name: Check Nginx Version
        run: C:\nginx\nginx-1.25.3\nginx.exe -v

      - name: Ensure Nginx Directories Exist
        shell: pwsh
        run: |
          if (!(Test-Path -Path "C:\nginx\nginx-1.25.3\logs")) {
            New-Item -ItemType Directory -Path "C:\nginx\nginx-1.25.3\logs"
          }
          if (!(Test-Path -Path "C:\nginx\nginx-1.25.3\conf")) {
            New-Item -ItemType Directory -Path "C:\nginx\nginx-1.25.3\conf"
          }

      - name: Debug Nginx Config Path
        shell: pwsh
        run: |
          if (Test-Path -Path "C:\nginx\nginx-1.25.3\conf\nginx.conf") {
            Write-Output "✅ nginx.conf file exists."
          } else {
            Write-Error "❌ nginx.conf file NOT found!"
          }

      - name: Update Nginx Configuration
        shell: pwsh
        run: |
          Copy-Item -Path "C:\nginx\nginx-1.25.3\conf\nginx.conf" -Destination "C:\nginx\conf\nginx.conf" -Force
          Start-Sleep -s 2
          C:\nginx\nginx-1.25.3\nginx.exe -s reload
