name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  # This will execute the existing tests

  deploy:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in workspace
        shell: pwsh
        run: Get-ChildItem -Path . -Recurse

      - name: Install PowerShell Core
        run: pwsh -c "Write-Output 'Using PowerShell Core'"

      - name: Run deployment script
        shell: pwsh
        working-directory: .github
        run: ./deploy_script.ps1

      - name: Download Nginx
        run: Invoke-WebRequest -Uri "https://nginx.org/download/nginx-1.25.3.zip" -OutFile "nginx.zip"

      - name: Extract Nginx
        run: Expand-Archive -Path nginx.zip -DestinationPath C:\nginx -Force

      - name: Ensure Nginx Extracted Correctly
        shell: pwsh
        run: |
          if (Test-Path -Path "C:\nginx\nginx-1.25.3\") {
            Write-Output "✅ Nginx extracted successfully."
          } else {
            Write-Error "❌ Nginx extraction failed."
          }

      - name: Check Nginx Version
        run: C:\nginx\nginx-1.25.3\nginx.exe -v

      - name: Ensure Nginx Directories Exist
        shell: pwsh
        run: |
          $nginxDir = "C:\nginx\nginx-1.25.3"
          if (!(Test-Path -Path "$nginxDir\logs")) {
            New-Item -ItemType Directory -Path "$nginxDir\logs" -Force
          }
          if (!(Test-Path -Path "$nginxDir\conf")) {
            New-Item -ItemType Directory -Path "$nginxDir\conf" -Force
          }

      - name: Debug Nginx Config Path
        shell: pwsh
        run: |
          if (Test-Path -Path "C:\nginx\nginx-1.25.3\conf\nginx.conf") {
            Write-Output "✅ nginx.conf file exists."
          } else {
            Write-Warning "⚠️ nginx.conf file NOT found here! Creating a default configuration."
            echo 'server { listen 80; server_name localhost; location / { root html; index index.html; } }' | Out-File -FilePath "C:\nginx\nginx-1.25.3\conf\nginx.conf"
          }

      - name: Update Nginx Configuration
        shell: pwsh
        run: |
          $nginxDir = "C:\nginx\nginx-1.25.3"
          Copy-Item -Path "$nginxDir\conf\nginx.conf" -Destination "$nginxDir\conf\nginx.conf.bak" -Force  # Backup old config
          Start-Sleep -s 2
          C:\nginx\nginx-1.25.3\nginx.exe -s reload
