name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # This will execute the existing tests

  deploy:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShell Core
        run: pwsh -c "Write-Output 'Using PowerShell Core'"

      - name: Run deployment script
        shell: pwsh
        run: |
          
          pwsh -ExecutionPolicy Bypass -File "./deploy_script.ps1"


      # - name: Deploy to Server
      #   run: |
          
      #      powershell -ExecutionPolicy Bypass -File "C:\Users\user\Documents\HNG projects\FastApi_Book\fastapi-book-project\deploy_script.ps1"

      - name: Update Nginx Configuration
        run: |
          # Update Nginx configuration if needed
            powershell -ExecutionPolicy Bypass -Command "Copy-Item 'C:\Users\user\Documents\nginx-1.26.3\nginx-1.26.3\conf\nginx.conf' 'C:\nginx\conf\nginx.conf' -Force; nginx -s reload"
