name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # This will execute the existing tests

  deploy:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in workspace
        shell: pwsh
        run: Get-ChildItem -Path . -Recurse

      - name: Install PowerShell Core
        run: pwsh -c "Write-Output 'Using PowerShell Core'"

      - name: Run deployment script
        shell: pwsh
        working-directory: .github
        run: ./deploy_script.ps1

      - name: Download Nginx
        run: Invoke-WebRequest -Uri "https://nginx.org/download/nginx-1.25.3.zip" -OutFile "nginx.zip"

      - name: Extract Nginx
        run: Expand-Archive -Path nginx.zip -DestinationPath C:\nginx

      - name: Check Nginx Version
        run: C:\nginx\nginx-1.25.3\nginx.exe -v

      - name: Ensure Nginx Directories Exist
        shell: pwsh
        run: |
          if (!(Test-Path -Path "C:\nginx\logs")) {
            New-Item -ItemType Directory -Path "C:\nginx\logs"
          }
          if (!(Test-Path -Path "C:\nginx\conf")) {
            New-Item -ItemType Directory -Path "C:\nginx\conf"
          }
      
      - name: Debug Nginx Config Path
        shell: pwsh
        run: |
          if (Test-Path -Path "C:\nginx\nginx-1.25.3\conf\nginx.conf") {
            Write-Output "✅ Source file exists."
          } else {
            Write-Error "❌ Source file NOT found! Check if Nginx is installed correctly."
          }
      
      - name: Update Nginx Configuration
        shell: pwsh
        run: |
          Copy-Item "C:\nginx\nginx-1.25.3\conf\nginx.conf" "C:\nginx\conf\nginx.conf" -Force 
          C:\nginx\nginx-1.25.3\nginx.exe -s reload
      
      # - name: Start Nginx with Correct Config
      #   shell: pwsh
      #   run: C:\nginx\nginx-1.25.3\nginx.exe -c C:\nginx\nginx-1.25.3\conf\nginx.conf