name: CD pipeline

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest  # Change to a Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t fastapi-app .

    - name: SSH to EC2 and deploy
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r . $USER@$HOST:/home/ubuntu/fastapi-book-project
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "cd /home/ubuntu/fastapi-book-project && docker build -t fastapi-app . && docker run -d -p 8000:8000 fastapi-app"