name: CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
  
    - name: Copy files to EC2
      run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" . ubuntu@16.170.224.134:/home/ubuntu/fastapi-book-project

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@16.170.224.134 "cd /home/ubuntu/fastapi-book-project && docker build -t fastapi-app . && docker run -d -p 8000:8000 fastapi-app"